# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Kat Connolly
title: Web Developer
email: katherine.d.connolly@gmail.com
website: https://katherineconnolly.com

# Social links
twitter_username: kate_kat_jpeg
github_username:  connka
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ahsoka.the.destroyer
linkedin_username: in/connollykd
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, I'm Kat. I'm currently working as a software engineer for Neo Financial in Calgary, Alberta. 
  In January 2019 I graduated from Lighthouse Labs' Web Development Bootcamp, and then spent 7 months helping them build their presence in Calgary. 
  But now it is time to get my hands dirty and write my own code. I am passionate about tech accessibilty and education. 
  In my spare time I volunteer with a local group called Chic Geek so I can spread that passion as far as possible. 

  I am most skilled in: <mark>React</mark> and <mark>HotDogs</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my software engineering and tech education some of my other interests and hobbies are:
   - Leather Work
   - Fiber Art
   - Video Editing
   - Eating Hot Dogs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
